apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qa
resources:
  - ../../bases/hola
  - namespace.yaml
transformers:
  - labels.yaml
configMapGenerator:
  - name: config_hola_domain
    literals:
      - HOLA_DOMAIN='hola-qa.opslab.local'
