name: Setup Go environment
on: [push, pull_request]

jobs:
  my_job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [ubuntu-latest]
    env:
      GOPATH: ${{ github.workspace }}/GOHOME
      GO11MODULE: off
      CGO_ENABLED: 0
      GOOS: linux
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: ${{ github.workspace }}/GOHOME/src/github.com/${{ github.repository }}
    - name: Setup Env
      uses: actions/setup-go@v2
      with:
        path: ${{ github.workspace }}/GOHOME
        go-version: ${{ matrix.go-version }}
    - name: GO Get 
      run: |
        go get github.com/rakyll/statik 
    - name: GO BUILD
      run: |
        cd ${{ github.workspace }}/GOHOME/src/github.com/${{ github.repository }}/hola/
        go build -ldflags="-w -s" -a -installsuffix cgo
    - name: Sent Noti
      uses: docker://dther/google-chat-action:latest
      with:
        msg: ${{ job.status }} ${{ github.repository }} ${{ github.event.name }} ${{ github.ref }} ${{ github.sha }} hello
        webhook: "https://chat.googleapis.com/v1/spaces/AAAAzPcAy4s/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=MmdzluicdrdkyUAV_QwB6BzlLcIhbfrwNzxVrEllaec%3D&threadKey=git-commit"
