name: Setup Go environment
on: [push, pull_request]

jobs:
  my_job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [ubuntu-latest]
    env:
      GOPATH: ${{ github.workspace }}/GOHOME
      GO11MODULE: off
      CGO_ENABLED: 0
      GOOS: linux
      CONTAINER_VERSION: v0.1
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: ${{ github.workspace }}/GOHOME/src/github.com/${{ github.repository }}
    - run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
      id: slug
    - name: Setup Env
      uses: actions/setup-go@v2
      with:
        path: ${{ github.workspace }}/GOHOME
        go-version: ${{ matrix.go-version }}
    - name: GO Get 
      run: |
        go get github.com/rakyll/statik 
    - name: GO BUILD
      run: |
        cd ${{ github.workspace }}/GOHOME/src/github.com/${{ github.repository }}/hola/
        go build -ldflags="-w -s" -a -installsuffix cgo
    - name: Docker Build & Push Image
      run: |
        cd ${{ github.workspace }}/GOHOME/src/github.com/${{ github.repository }}/hola/
        echo "${{ secrets.DOCKERPW }}" | docker login -u "dther" --password-stdin
        docker image build -t dther/web-app-flux:${{ CONTAINER_VERSION }} .
        docker push dther/web-app-flux:${{ CONTAINER_VERSION }}
    - name: Sent Noti
      if: ${{ always() }}
      uses: DTherHtun/google-chat-action@v0.8
      with:
        project: ${{ github.repository }}
        commit: ${{ steps.slug.outputs.sha8 }}
        branch: ${{ github.ref }}
        status: ${{ job.status }}
        actionid: ${{ github.repository }}/actions/runs/${{ github.run_id }}
        webhook: "https://chat.googleapis.com/v1/spaces/AAAAzPcAy4s/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=MmdzluicdrdkyUAV_QwB6BzlLcIhbfrwNzxVrEllaec%3D&threadKey=git-commit"
