name: Setup Go environment
on: [push, pull_request]

jobs:
  my_job:
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [ubuntu-latest]
    env:
      GOPATH: ${{ github.workspace }}
      GO11MODULE: off
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Env
      uses: actions/setup-go@v2
      with:
        path: ./src/github.com/${{ github.repository }}
        go-version: ${{ metrix.go-version }}
    - name: GO Get 
      run: |
        cd ./src/github.com/${{ github.repository }}/hola/
        go get github.com/rakyll/statik 
        CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -a -installsuffix cgo
