name: Setup Go environment
on: [push, pull_request]

jobs:
  my_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [ubuntu-latest]
    env:
      GOPATH: ./src/github.com/
      GO11MODULE: off
      CGO_ENABLED: 0
      GOOS: linux
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: ./src/github.com/${{ github.repository }}
    - name: Setup Env
      uses: actions/setup-go@v2
      with:
        path: ./src/github.com/${{ github.repository }}
        go-version: ${{ matrix.go-version }}
    - name: GO Get 
      run: |
        cd ./src/github.com/${{ github.repository }}/hola/
        go get github.com/rakyll/statik 
        go build -ldflags="-w -s" -a -installsuffix cgo
